### ISSUE TITLE
Tests are failing with beautifulsoup4 >= 4.7

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.catalog#8] opened 2019-02-02 08:51 UTC
Up to version 4.6.x everything is fine. 4.7+ breaks with a strange error message:

```python
File "/home/travis/build/zopefoundation/zc.catalog/src/zc/catalog/browser/README.rst", line 20, in README.rst
Failed example:
    browser.getControl('Catalog').click()
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/2.7.14/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest README.rst[7]>", line 1, in <module>
        browser.getControl('Catalog').click()
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 383, in getControl
        include_subcontrols=True)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 404, in _getAllControls
        res = self._findByLabel(label, forms, include_subcontrols)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 423, in _findByLabel
        for l in wtcontrol.labels:
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/cachedescriptors/property.py", line 106, in __get__
        value = func(inst)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 1147, in labels
        for l in getControlLabels(self._elem, self._form.html)]
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/zope/testbrowser/browser.py", line 1370, in getControlLabels
        forlbls = html.select('label[for=%s]' % controlid)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/bs4/element.py", line 1376, in select
        return soupsieve.select(selector, self, namespaces, limit, **kwargs)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/__init__.py", line 108, in select
        return compile(select, namespaces, flags).select(tag, limit)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/__init__.py", line 59, in compile
        return cp._cached_css_compile(pattern, namespaces, flags)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 137, in wrapper
        result = user_function(*args, **kwds)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/css_parser.py", line 175, in _cached_css_compile
        CSSParser(pattern, flags).process_selectors(),
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/css_parser.py", line 807, in process_selectors
        return self.parse_selectors(self.selector_iter(self.pattern), index, flags)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/css_parser.py", line 685, in parse_selectors
        key, m = next(iselector)
      File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/soupsieve/css_parser.py", line 794, in selector_iter
        raise SyntaxError("Invlaid character {!r} at position {}".format(pattern[index], index))
    SyntaxError: Invlaid character u'[' at position 5
```

(Example taken from https://travis-ci.org/zopefoundation/zc.catalog/jobs/474040741)

Maybe this is a bug in `beautifulsoup4` or `zope.testbrowser`.

**Comment by facelessuser** [comment] 2019-02-02 14:34
Hi, I am the author of Soup Sieve, the new library that replaces Beautiful Soup's old CSS select implementation in version 4.7.0+. I've been doing occasional searches for issues with `soupsieve` so that I can help with the transition.

Soup Sieve aims to follow the CSS specification for selectors in order to ensure we can support selectors that may come in the future. One of the side effects is that there are a couple of quirks of BS4's select implementation that people have relied on that were not covered in BS4's tests, so they were not caught before release.  The issues are explained in a fair amount of detail here: https://facelessuser.github.io/soupsieve/#beautiful-soup-differences.

Soup Sieve 1.7.3 actually gives a better error description than what you are seeing above. Unfortunately ` SyntaxError: Invlaid character u'[' at position 5` is not really that helpful, but what is happening is that Soup Sieve expects CSS attribute values to follow the CSS spec which require the value in `[attribute=value]` to either be an unquoted, valid identifier token, or they must be quoted. That means things like `[attribute=some value]` or `[attribute={}]` are invalid and must be quoted: `[attribute="some value"]` or `[attribute="{}"]`.  By following the specification, it allows us to implement new CSS level 4 selectors, such as forced case insensitivity for attribute values : `[attribute=value i]`.

I would recommend, if you use the latest Beautiful Soup, to require Beautiful Soup  4.7.1 and Soup Sieve 1.7.3 as most issues have been worked out in those two releases. You are also welcome to lock Beautiful Soup to the 4.6 series as well if you are not yet ready to deal with the new changes.

On the next Beautiful Soup release, the failure you are experiencing will actually issue a warning instead of an error as Soup Sieve will be run in a "quirks" mode.  The support is already  in Soup Sieve to allow for a "quirks" mode for a limited time, but Beautiful Soup has not issued a release that takes advantage of the new "quirks" mode.

Hopefully this helps. In short, what you are experiencing is not a bug in Beautiful Soup per se, but an exposing of improper CSS that has in the past gone unchecked.

**Comment by mgedmin** [comment] 2019-02-04 10:43
@facelessuser thank you for jumping in!

Indeed, SoupSieve 1.7.3 gives a different message:

> SyntaxError: Malformed attribute selector at position 5

Luckily the actual selector can be seen several frames up in the traceback

```
      File "/home/mg/.cache/buildout/eggs/zope.testbrowser-5.3.1-py2.7.egg/zope/testbrowser/browser.py", line 1370, in getControlLabels
        forlbls = html.select('label[for=%s]' % controlid)
```

So this incompatibility has to be fixed in zope.testbrowser rather than in zc.catalog.

**Comment by mgedmin** [comment] 2019-02-04 10:47
Filed https://github.com/zopefoundation/zope.testbrowser/issues/61

**Comment by mgedmin** [comment] 2019-02-05 14:45
With https://github.com/facelessuser/soupsieve/pull/103 I can see the actual selector that fails here:

> label[for=BrowserAdd__zope.catalog.catalog.Catalog]

**Comment by mgedmin** [comment] 2019-02-06 13:56
I've released zope.testbrowser 5.3.2 that should fix this issue.

**Closed as completed** 2019-02-06 13:57 UTC
Labels: bug

**Comment by icemac** [comment] 2019-02-07 11:06
@mgedmin Thank you!
